version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.13
  pre_build:
    commands:
      - echo "Current directory:"
      - pwd
      - echo "Listing all files:"
      - ls -R
      - echo "Installing dependencies..."
      - pip install -r Leonidas_Learning/my-project-n-01/requirements.txt
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" Leonidas_Learning/my-project-n-01
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: Leonidas_Learning/my-project-n-01
